version: "3.8"

services:
  kafka:
    image: docker.io/apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # KRaft single-node
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LOG_DIRS=/tmp/kraft-combined-logs

  kafka-ui:
    image: docker.io/provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    extra_hosts:
      - "host.containers.internal:host-gateway"
      - "kafka:host-gateway"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=host.containers.internal:9092

  spark:
    build:
      context: .
    image: toxicity-spark:local
    container_name: spark
    depends_on:
      - kafka
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
    volumes:
      - ./:/opt/app
      - ./spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro
    working_dir: /opt/app
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
      --host spark
      --port 7077
      --webui-port 8080

  spark-worker:
    image: toxicity-spark:local
    depends_on:
      - spark
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
    volumes:
      - ./:/opt/app
      - ./spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro
    working_dir: /opt/app
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker
      spark://spark:7077
